### PR TITLE
Fix/Reset AudioStreamingIndicator to PLAY_PAUSE

### LINKED ISSUE #517: HMI does not set default "PLAY_PAUSE" playback indicator in case App request SetMediaClockTimer without audioStreamingIndicator parameter
HMI does not set default "PLAY_PAUSE" playback indicator in case App request SetMediaClockTimer without audioStreamingIndicator parameter 

**Precondition:**
    1. SDL and HMI are started
    2. App with HMI type 'Media' is registered
    3. App is activated
    4. App sends SetMediaClockTimer RPC with:
      "updateMode":"COUNTUP",
      "startTime": { "hours":0, "minutes":15, "seconds":30 },
      "audioStreamingIndicator":"PAUSE"
    5. The seek indicators are "PAUSE" for App
    'PLAY_PAUSE' button with "ico_pause.png" image is observed on HMI

**Steps to reproduce:**
1. Send SetMediaClockTimer RPC without audioStreamingIndicator:
"updateMode":"COUNTUP",
"startTime": { "hours":0, "minutes":15, "seconds":30 }

**Expected result:**
1. HMI sets default "PLAY_PAUSE" playback indicator
'PLAY_PAUSE' button with "ico_play_pause.png" image is observed on HMI

**Actual result:**

1. HMI does not set default "PLAY_PAUSE" playback indicator
'PLAY_PAUSE' button with "ico_pause.png" image is observed on HMI
Image

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/develop (fed2ae4)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (ad2dc80)
SPT: 20210305-Android (1076)

### PR DESCRIPTION
**Pull request by ShobhitAd**
Implements/Fixes #517

This PR is **ready** for review.

### Testing Plan
Run reproduction steps using Test Suite/RPC Builder app

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: ffw/UIRPC.js [hunk 1]
```diff
@@ -412,9 +412,18 @@ FFW.UI = FFW.RPCObserver.create(
...
               if(request.params.audioStreamingIndicator) {
                 SDL.SDLController.SetAudioStreamingIndicator(request.params)
+              } 
+              else if (SDL.SDLController.model.mediaPlayerIndicator !== 
+                SDL.SDLModel.data.mediaPlayerIndicatorEnum.PLAY_PAUSE) {                
+                modifiedParams = Object.assign({}, request.params, {
+                  "audioStreamingIndicator": "PLAY_PAUSE"
+                });
+                SDL.SDLController.SetAudioStreamingIndicator(modifiedParams)
               }
```
Comment (jacobkeeler) [inline ffw/UIRPC.js:425]:
```suggestion
              
              var indicator = request.params.audioStreamingIndicator ? request.params.audioStreamingIndicator : "PLAY_PAUSE"
              SDL.SDLController.SetAudioStreamingIndicator(indicator)

```
Seems a bit odd to be sending in a modified version of the message. I would suggest editing the function to take in the indicator rather than the full message, as most of it is unused in the function at the moment

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Comment by ShobhitAd** [comment]
@jacobkeeler Applied suggested change. Also added change to reset audioStreamingIndicator to PLAY_PAUSE when app enters HMI_NONE (as specified in the proposal https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0109-set-audio-streaming-indicator.md#hmi--mobile-api)

File: ffw/UIRPC.js [hunk 2]
```diff
@@ -1662,7 +1664,7 @@ FFW.UI = FFW.RPCObserver.create(
           }
           case 'UI.SetAudioStreamingIndicator':
```
Comment (jacobkeeler) [inline ffw/UIRPC.js:1665]: Looks like this might've been from before the project became open-source. This RPC does not exist. Probably best to just remove this case

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

**Review by jacobkeeler — APPROVED** [review]
