### PR TITLE
Fix AlertManeuer soft buttons behavior

### LINKED ISSUE #346: HMI does not perform predefined actions by clicking the custom softButtons on AlertManeuver pop-up
### Bug Report
HMI does not perform predefined actions by clicking the custom softButtons on AlertManeuver  pop-up

##### Reproduction Steps
1. Start SDL and HMI
2. AlertManeuver is allowed by policies
3. Mobile app is registered and activated
4. App requests `AlertManeuver` with softButtons
5. Request is processed successfully by SDL and is resent to HMI
6. Press custom button

##### Expected Behavior
HMI shows AlertManeuver pop-up only with custom softButtons.
According to pressed button type HMI should perform the next actions:
`DEFAULT_ACTION` - Default action occurs.  Standard behavior (e.g. SoftButton clears overlay)
`STEAL_FOCUS` - The calling app's dialog or related event should clear and the app should be brought into HMI_FULL
`KEEP_CONTEXT` - Current system context is maintained.  An overlay is persisted even though a SoftButton has been pressed and the notification sent

##### Observed Behavior
AlertManeuver pop-up is shown with custom and system defined "Close" SoftButtons.
HMI sends only `Buttons.OnButtonEvent` and `Buttons.OnButtonPress` by pressing custom button and performs predefined actions only by pressing system defined "Close" SoftButton.

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e5743afe5193fcd9bc667d5d48a6220552345a97
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #346 

This PR is **not ready** for review.

### Testing Plan
Covered by manual testing plan

### Summary
The following changes were done to implement this behavior:
- Timeout and request id fields were moved outside the function as it can be called from a several places
- Added correct values for `groupName` and `appID` fields for `AlertManeuer` preset buttons
- Was created separate function for `AlertManeuer` popup proper deactivate including TTS stop
- Controller were extended to handle preset events from group of buttons on `AlertManeuer` popup

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/controller/sdl/Abstract/Controller.js [hunk 1]
```diff
@@ -638,6 +649,17 @@ SDL.SDLController = Em.Object.extend(
           this.onResetTimeout(element.appID, 'UI.Alert');
           break;
         }
+        case 'AlertManeuverPopUp':
+        {
+          clearTimeout(SDL.AlertManeuverPopUp.timer);
+          SDL.AlertManeuverPopUp.timer = setTimeout(
+            function() {
+              SDL.AlertManeuverPopUp.deactivate();
```
Comment (mkorniichuk) [inline app/controller/sdl/Abstract/Controller.js:657]: @AKalinich-Luxoft There is already one timer in AlertManeuverActive. Isn't this one redundant?

Comment (AKalinich-Luxoft) [reply app/controller/sdl/Abstract/Controller.js:657]: @mkorniichuk this function is actually restarts timer which was started in AlertManeuverActive.
When user click on button with action KEEP_CONTEXT, HMI should restart timer with the initial timeout.

**Comment by AKalinich-Luxoft** [comment]
@iCollin conflicts have been resolved in https://github.com/smartdevicelink/sdl_hmi/pull/348/commits/728125a0030185e1a539d808fd0413a50a1141e8

**Review by iCollin — APPROVED** [review]
