### PR TITLE
Fix switching between non-media and media templates

### LINKED ISSUE #535: HMI applies the same display layout for Media and Non-media in case of layout setting via SetDisplayLayout
**Description:**
HMI applies the same display layout for Media and Non-media in case of layout setting via SetDisplayLayout

**Precondition:**
1. SDL and HMI are started
2.  Media mobile app is registered and activated

**Steps to reproduce:**
1. Mobile app requests SetDisplayLayout(displayLayout = non-media)

**Expected result:**
HMI applies non-media template

**Actual result:**
HMI does not update the layout

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #535 

This PR is **ready** for review.

### Testing Plan
Manually test switching between templates with various combinations of the `MEDIA` and `NAVIGATION` app types. Verify that app info is displayed properly.

### Summary
Allows media apps to properly use the non-media template. Adds restrictions for `MEDIA`, `NAV_FULLSCREEN_MAP`, and `WEB_VIEW` templates based on app type.

Also removes redundant/unused app model fields.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/model/sdl/Abstract/Model.js [hunk 1]
```diff
@@ -614,13 +595,45 @@ SDL.SDLModel = Em.Object.extend({
...
+   */
+  isTemplateSupported: function(model, template) {
+    switch (template) {
+      case 'MEDIA':
+      {
+        return model.isMedia === true;
+      }
+      case 'NAV_FULLSCREEN_MAP':
+      {
+        return model.appType.indexOf('NAVIGATION') >= 0;
```
Comment (JackLivio) [inline app/model/sdl/Abstract/Model.js:621]: Also check if type is PROJECTION?

Comment (jacobkeeler) [reply app/model/sdl/Abstract/Model.js:621]: Hmmm, a little surprised there isn't a specific template for that sort of thing, but it does look like PROJECTION should probably be allowed in this case, yeah

**Review by JackLivio — APPROVED** [review]
