### PR TITLE
Fix/fix type error on file remove

### LINKED ISSUE #300: TypeError by file deleting
### Bug Report
TypeError by file deleting

##### Reproduction Steps
1. Start SDL and HMI
2. Mobile app adds file by PutFile RPC
3.Some RPC is processed with added file
4. Mobile app requests DeleteFile

##### Expected Behavior
HMI receives BC.OnFileRemoved and there are no error messages in HMI console

##### Observed Behavior
HMI receives BC.OnFileRemoved and logs the error
```
TypeError: SDL.SDLController.getApplicationModel(...).globalProperties.vrHelp[i].image is undefinedModel.js:353:1
    onFileRemoved file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/app/model/sdl/Abstract/Model.js:353
    onRPCNotification file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/BasicCommunicationRPC.js:431
    d Ember
    onWSMessage file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/RPCClient.js:168
    onmessage file:///home/developer/sdl/repo/SDLMirror/sdl_hmi/ffw/RPCClient.js:81
```

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

##### HMI log
[hmi.log](https://github.com/smartdevicelink/sdl_hmi/files/4425673/hmi.log)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #300 

This PR is **ready** for review.

### Testing Plan
Covered with manual testing

### Summary
Changelog:
- Replaced multiple getters with a single variable referring to the same object.
- Added one more check to verify if `vrHelp` item contains `image` object or not as it might be not mandatory according to HMI_API

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/model/sdl/Abstract/Model.js [hunk 1]
```diff
@@ -200,48 +200,30 @@ SDL.SDLModel = Em.Object.extend({
   onFileRemoved: function(params) {
 
     var result = false;
+    var app_model = SDL.SDLController.getApplicationModel(params.appID);
 
     if ((
       params.fileType === 'GRAPHIC_PNG' || params.fileType === 'GRAPHIC_BMP' ||
```
Comment (YarikMamykin) [inline app/model/sdl/Abstract/Model.js:206]: @AKalinich-Luxoft , I would advise to place condition `(params.fileType === 'GRAPHIC_PNG' || params.fileType === 'GRAPHIC_BMP' || params.fileType === 'GRAPHIC_JPEG')` into a single variable...

Or even make some lambda for that purpose, e.g:
```suggestion
      var file_is_pic = function (fileType) {
        var check_list = [ 'GRAPHIC_PNG', 'GRAPHIC_BMP', 'GRAPHIC_JPEG' ]
        for (var item in check_list) {
          if (fileType === item) {
            return true;
          }
        }
        return false;
      }
```

Comment (AKalinich-Luxoft) [reply app/model/sdl/Abstract/Model.js]: @YarikMamykin good idea. However lambda is overhead here.
See https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/ea6d7cf4860d59ef8e18d78749a13ae26bdaa0f3

File: app/model/sdl/Abstract/Model.js [hunk 2]
```diff
@@ -200,48 +200,29 @@ SDL.SDLModel = Em.Object.extend({
...
-          params.fileName.length == SDL.SDLController.getApplicationModel(
-            params.appID
-          ).constantTBTParams.turnIcon.value.length) {
-          SDL.SDLController.getApplicationModel(params.appID
-          ).constantTBTParams.turnIcon.value            =
-              SDL.SDLModel.data.defaultListOfIcons.command;
+      if (app_model.constantTBTParams) {
+        if (app_model.constantTBTParams.turnIcon &&
+            app_model.constantTBTParams.turnIcon.value.indexOf(params.fileName) != -1 &&
+          params.fileName.length == app_model.constantTBTParams.turnIcon.value.length) {
```
Comment (ShobhitAd) [inline app/model/sdl/Abstract/Model.js:217]: Wouldn't you get the same result if you replaced these conditions with 
```suggestion
            app_model.constantTBTParams.turnIcon.value === params.fileName) {
```

**Review by ShobhitAd — CHANGES_REQUESTED** [review]

**Comment by theresalech** [comment]
Hi @AKalinich-Luxoft, we are nearing the end of our development timeline and will need to merge this PR by EOD Monday (10/26) in order to guarantee its inclusion in the SDL HMI 5.4 Release. Can you please let us know if you have any concerns with addressing our review on this PR by that time? Thank you!

File: app/model/sdl/Abstract/Model.js [hunk 3]
```diff
@@ -200,48 +200,29 @@ SDL.SDLModel = Em.Object.extend({
...
-      if (SDL.SDLController.getApplicationModel(params.appID).appIcon.
-              indexOf(params.fileName) != -1 &&
-        params.fileName.length ==
-        SDL.SDLController.getApplicationModel(params.appID).appIcon.length) {
-        SDL.SDLController.getApplicationModel(params.appID).
-            set('appIcon', SDL.SDLModel.data.defaultListOfIcons.app);
+    if (is_image_type && app_model) {
+      result = app_model.onImageRemoved(params.fileName);
+
+      if (app_model.appIcon.indexOf(params.fileName) != -1 &&
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply app/model/sdl/Abstract/Model.js]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/122e39649b6c14a42f13bac8cd4a6412d75fb591

File: app/model/sdl/Abstract/Model.js (hunk 2 above)
Comment (AKalinich-Luxoft) [reply app/model/sdl/Abstract/Model.js]: @ShobhitAd agree, you suggestion is much obvious. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/332/commits/122e39649b6c14a42f13bac8cd4a6412d75fb591

**Comment by AKalinich-Luxoft** [comment]
> Hi @AKalinich-Luxoft, we are nearing the end of our development timeline and will need to merge this PR by EOD Monday (10/26) in order to guarantee its inclusion in the SDL HMI 5.4 Release. Can you please let us know if you have any concerns with addressing our review on this PR by that time? Thank you!

@theresalech thank you for letting me know! I addressed all Livio comments and hopefully you will be able to review and approve this PR soon.

**Review by ShobhitAd — APPROVED** [review]
