### PR TITLE
Fix/Check priority ranking when there is an existing alert

### LINKED ISSUE #290: Alert RPC ignores app priority
According to the Core Certification Guidelines (found here: https://smartdevicelink.com/resources/, Smoke Test - 29), Alerts are supposed to take app priority into account. If an app with a higher priority (determined by its priority value position in the `AppPriority` enum [defined here](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L1449-L1456)), sends an Alert while an app of lower priority has an Alert active, the lower priority app should be sent an `ABORTED` response and the higher priority app's alert should take precedence.

Reproduction steps:
1. Connect app1 with `Notifications` permissions (allowing `Alert` RPC in background) and priority `NORMAL`, both configurable in the policy table for this app.
2. Connect app2 with `Notifications` permissions and priority `COMMUNICATION`.
3. Activate app2
4. Return to app menu, activate app1 (putting app2 into `BACKGROUND` HMI level)
5. Send `Alert` RPC from app1, alert appears on-screen
6. While the first alert is active, send `Alert` request from app2

Expected Behavior:
1. First alert is dismissed, app1 received `Alert` response with `ABORTED`
2. app2's alert appears on-screen

Actual Behavior:
1. First alert remains active, app2 receives `Alert` response with `REJECTED`

### PR DESCRIPTION
**Pull request by ShobhitAd**
Implements/Fixes #290

This PR is **ready** for review.

### Testing Plan
Reproduce steps in issue with test_suite app

### Summary
1. Add priority property to app model struct
2. Add enum for app priority values
3. Add priority check in `onUIAlert`

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/controller/sdl/Abstract/Controller.js [hunk 1]
```diff
@@ -919,7 +919,8 @@ SDL.SDLController = Em.Object.extend(
               dayColorScheme: isDayColorSchemeDefined ? params.dayColorScheme : SDL.SDLModelData.data.defaultColorScheme,
               nightColorScheme: isNightColorSchemeDefined ? params.nightColorScheme : SDL.SDLModelData.data.defaultColorScheme,
               policyAppID: params.policyAppID,
-              webEngineApp: isWebEngineApp
+              webEngineApp: isWebEngineApp,
+              priority: params.priority
```
Comment (iCollin) [inline app/controller/sdl/Abstract/Controller.js:923]:
```suggestion
              priority: params.priority ? params.priority : 'NONE'
```

File: app/controller/sdl/Abstract/Controller.js [hunk 2]
```diff
@@ -938,7 +939,8 @@ SDL.SDLController = Em.Object.extend(
...
```
Comment (iCollin) [inline app/controller/sdl/Abstract/Controller.js:943]:
```suggestion
              priority: params.priority ? params.priority : 'NONE'
```

File: app/controller/sdl/RController.js [hunk 3]
```diff
@@ -308,7 +308,8 @@ SDL.RController = SDL.SDLController.extend(
               dayColorScheme: "dayColorScheme" in params ? params.dayColorScheme : SDL.SDLModelData.defaultTemplateColorScheme,
               nightColorScheme: "nightColorScheme" in params ? params.nightColorScheme : SDL.SDLModelData.defaultTemplateColorScheme,
               policyAppID: params.policyAppID,
-              webEngineApp: isWebEngineApp
+              webEngineApp: isWebEngineApp,
+              priority: params.priority
```
Comment (iCollin) [inline app/controller/sdl/RController.js:312]:
```suggestion
              priority: params.priority ? params.priority : 'NONE'
```

File: app/controller/sdl/RController.js [hunk 4]
```diff
@@ -329,7 +330,8 @@ SDL.RController = SDL.SDLController.extend(
               dayColorScheme: "dayColorScheme" in params ? params.dayColorScheme : SDL.SDLModelData.data.defaultColorScheme,
               nightColorScheme: "nightColorScheme" in params ? params.nightColorScheme : SDL.SDLModelData.data.defaultColorScheme,
               policyAppID: params.policyAppID,
-              webEngineApp: isWebEngineApp
+              webEngineApp: isWebEngineApp,
+              priority: params.priority
```
Comment (iCollin) [inline app/controller/sdl/RController.js:334]:
```suggestion
              priority: params.priority ? params.priority : 'NONE'
```

File: app/controller/sdl/RController.js [hunk 5]
```diff
@@ -348,7 +350,8 @@ SDL.RController = SDL.SDLController.extend(
               dayColorScheme: "dayColorScheme" in params ? params.dayColorScheme : SDL.SDLModelData.defaultTemplateColorScheme,
               nightColorScheme: "nightColorScheme" in params ? params.nightColorScheme : SDL.SDLModelData.defaultTemplateColorScheme,
               policyAppID: params.policyAppID,
-              webEngineApp: isWebEngineApp
+              webEngineApp: isWebEngineApp,
+              priority: params.priority
```
Comment (iCollin) [inline app/controller/sdl/RController.js:354]:
```suggestion
              priority: params.priority ? params.priority : 'NONE'
```

File: ffw/BasicCommunicationRPC.js [hunk 6]
```diff
@@ -500,8 +500,9 @@ FFW.BasicCommunication = FFW.RPCObserver
           }
         }
         if (notification.method == this.onAppRegisteredNotification) {
+          let appModel = Object.assign(notification.params.application, {"priority": notification.params.priority});
```
Comment (iCollin) [inline ffw/BasicCommunicationRPC.js:503]:
```suggestion
          let appModel = Object.assign(notification.params.application, {"priority": notification.params.priority ? notification.params.priority : 'NONE'}); 
```

you may want to make this multiple lines :)
