### PR TITLE
Fix usage of SDL model

### LINKED ISSUE #259: Uncaught TypeError
### Bug Report
Uncaught TypeError

##### Reproduction Steps
1. Hit `Put File`
2. Tap `...` next to the `Local File Name` field
3. Select a photo on your phone
4. Leave file type as `GRAPHIC_BMP`
6. Hit SEND
7. Hit `DeleteFile`
8. Select from dropdown list file
9. Hit SEND

##### Expected Behavior
In the console of HMI does not displayed error after successful delete of file

##### Observed Behavior
In the console see Uncaught TypeError after successful delete of file

##### OS & Version Information
SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (4d283e6)
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop
(commit: bd53f11339ee4d95a41caf5e5edf4ae0839d5957) 

##### Attachments
[error in the HMI console.tar.gz](https://github.com/smartdevicelink/sdl_hmi/files/3845882/error.in.the.HMI.console.tar.gz)

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #259 

This PR is **ready** for review.

### Testing Plan
Manual testing by steps, described in https://github.com/smartdevicelink/sdl_hmi/issues/259

### Summary
After DeleteFile RPC is started on HMI, SDL.SDLController.model object can be null.
Added appropriate check for this issue.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/model/sdl/Abstract/Model.js [hunk 1]
```diff
@@ -246,24 +246,27 @@ SDL.SDLModel = Em.Object.extend({
...
-        SDL.SDLController.model.appInfo.mainImage.length) {
-        SDL.SDLController.model.appInfo.set('mainImage',
-          SDL.SDLModel.data.defaultListOfIcons.trackIcon
-        );
+      if (SDL.SDLController.model) {
+        if (SDL.SDLController.model.appInfo.trackIcon &&
+          SDL.SDLController.model.appInfo.trackIcon.indexOf(params.fileName) !=
+          -1 &&
+          params.fileName.length ==
+          SDL.SDLController.model.appInfo.trackIcon.length) {
```
Comment (mked-luxoft) [inline app/model/sdl/Abstract/Model.js]: maybe it's worth to refactor these huge if statements to bool variables?

Comment (YarikMamykin) [reply app/model/sdl/Abstract/Model.js]: @mked-luxoft , do you mean like this caf59541a551b62f4142454f867e1672d8166464?

File: app/model/sdl/Abstract/Model.js [hunk 2]
```diff
@@ -246,24 +246,27 @@ SDL.SDLModel = Em.Object.extend({
...
-        -1 &&
-        params.fileName.length ==
-        SDL.SDLController.model.appInfo.mainImage.length) {
-        SDL.SDLController.model.appInfo.set('mainImage',
-          SDL.SDLModel.data.defaultListOfIcons.trackIcon
-        );
+      if (SDL.SDLController.model) {
+        var appInfoValid = (SDL.SDLController.model.appInfo.trackIcon != null);
+        var paramFileNameValid = (SDL.SDLController.model.appInfo.trackIcon.indexOf(params.fileName) != -1);
+        var fileNameLengthValid = (params.fileName.length == SDL.SDLController.model.appInfo.trackIcon.length);
```
Comment (jacobkeeler) [inline app/model/sdl/Abstract/Model.js]: I might suggest removing this condition, since a recent change might make this check fail otherwise. A modification time was added to the filename if a file is updated, so the length might be different: https://github.com/smartdevicelink/sdl_hmi/pull/185/files#diff-0d963eeead5b1093554377efe7446aeeR389.

Another workaround which might work here is
```
var icon = SDL.SDLController.model.appInfo.trackIcon;
var modTimeIndex = icon.indexOf("?m=");
if (modTimeIndex != -1) {
  icon = icon.substring(0, modTimeIndex)
}
var fileNameLengthValid = (params.fileName.length == icon.length);
```

Comment (YarikMamykin) [reply app/model/sdl/Abstract/Model.js]: @jacobkeeler , please take a look at https://github.com/smartdevicelink/sdl_hmi/pull/260/commits/c5ee713c701c55c5f24a0f33825e8f64989858db

File: app/model/sdl/Abstract/Model.js [hunk 3]
```diff
@@ -246,24 +246,32 @@ SDL.SDLModel = Em.Object.extend({
...
-          SDL.SDLModel.data.defaultListOfIcons.trackIcon
-        );
+      if (SDL.SDLController.model) {
+        var getFileName = function(complexFileName) {
+          var dateTimeSeparator = "?m=";
+          var modTimeIndex = complexFileName.indexOf(dateTimeSeparator);
+          if (modTimeIndex != -1) {
+            return complexFileName.substring(0, modTimeIndex);
+          }
+          return "";
```
Comment (jacobkeeler) [inline app/model/sdl/Abstract/Model.js]:
```suggestion
          return complexFileName;
```

File: app/model/sdl/Abstract/Model.js (hunk 2 above)
Comment (jacobkeeler) [reply app/model/sdl/Abstract/Model.js]: @YarikMamykin why did you remove the `appInfoValid` and `paramFileNameValid` checks?

File: app/model/sdl/Abstract/Model.js (hunk 3 above)
Comment (YarikMamykin) [reply app/model/sdl/Abstract/Model.js]: @jacobkeeler , fixed in a4bcb009dc2075a87f0f7bff8ba9eb8cecb4c759

File: app/model/sdl/Abstract/Model.js (hunk 2 above)
Comment (YarikMamykin) [reply app/model/sdl/Abstract/Model.js]: @jacobkeeler , fixed in a4bcb009dc2075a87f0f7bff8ba9eb8cecb4c759
