### PR TITLE
Find correct preferred resolution with scale

### LINKED ISSUE #547: Incorrect video streaming resolution after changing it via json editor
**Description:**
Incorrect video streaming resolution after changing it via json editor

**Precondition:**
1. HMI and SDL are started
2. Navigation mobile app is registered

**Steps to reproduce:**
1. Mobile app starts video streaming
2. Go to HMI main menu
3. Menu item `Send VIDEO_STREAMING capabilities`
4. Update video capabilities to any preferred resolution values (for example "resolutionWidth": 320, "resolutionHeight": 200)
5. Press `Send notification`
**Note: HMI shows video with the wrong resolution also in case when the mobile app starts stream with the resolution different from the default(800*480)**

**Expected behavior:**
Mobile app starts streaming with the new resolution 320x200
HMI shows streaming with new resolution 320x200
```
Switching video streaming preset to: 320x200
FFW.BasicCommunication.OnSystemCapabilityUpdated
HMI -> SDL: 
BC.OnSystemCapabilityUpdated(systemCapability = {"preferredResolution":{"resolutionWidth":320,"resolutionHeight":200}}, appId)
```
image
image

**Actual result:**
HMI displays video streaming with the wrong resolution
```
FFW.BasicCommunication.OnSystemCapabilityUpdated
HMI -> SDL: 
BC.OnSystemCapabilityUpdated(systemCapability = {"preferredResolution":{"resolutionWidth":320,"resolutionHeight":200}}, appId)
```
image
*Note:* If the resolution has been changed using drop-down list - streaming resolution is correct 
If the resolution has been changed using `json` editor - streaming resolution isn't correct

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/commits/release/5.5.0 (b1d31f8)

### PR DESCRIPTION
**Pull request by JackLivio**
Implements/Fixes #547 

This PR is **ready** for review.

### Testing Plan
App starts stream with non-default/preferred resolution.

### Summary
The resolutions in the sdl hmi use the scale parameter in their name, so this effects the changes included in #552 where the scaling parameter does not exist in the setVideoConfig request. HMI will make an attempt to find the resolution with the last set scale, or find the resolution that does not include a scaling parameter.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: ffw/NavigationRPC.js [hunk 1]
```diff
@@ -326,18 +326,33 @@ FFW.Navigation = FFW.RPCObserver.create(
...
+                    resolutionHeight: height
+                  },
+                  scale: scale
+                });
+                const preset_list = SDL.NavigationController.getVideoStreamingCapabilitiesList();
+                const index = preset_list.indexOf(preferred);
+                Em.Logger.log("App Preferred Index: " + index)
+                if (index >= 0 && index !== app_model.resolutionIndex) {
+                  Em.Logger.log(`Switching video streaming preset to: ${preferred}`);
+                  SDL.NavigationController.model.set('resolutionIndex', index);
```
Comment (AKalinich-Luxoft) [inline ffw/NavigationRPC.js:342]: @JackLivio issue is still seen with that fix. Looks like you are trying to set resolution index in a generic data model, but not for a specific application model. It won't work because resolution index property has been moved to application model. You should change it to:
```suggestion
app_model.set('resolutionIndex', index);
```

Comment (AKalinich-Luxoft) [reply ffw/NavigationRPC.js:342]: @JackLivio with the suggested changes it works as expected on my side

**Comment by AKalinich-Luxoft** [comment]
@JackLivio are you going to remove/deactivate editor according to comment mentioned in the linked issue?

File: ffw/NavigationRPC.js (hunk 1 above)
Comment (JackLivio) [reply ffw/NavigationRPC.js]: @AKalinich-Luxoft Thank you for the suggestion! Comitted
