### PR TITLE
Fix/Handling ButtonPress for SOURCE button

### LINKED ISSUE #692: Audio SOURCE switching in HMI_FULL causes UI issue
## Description:
Switching the Audio SOURCE while the app is in HMI full results in a weird UI state

### Precondition:

1. Add remote control permissions in the preloaded_pt
```json
"app_policies": {
            "default": {
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": [
                    "Base-4", "RemoteControl"
                ],
                "moduleType": [],
                "RequestType": [],
                "RequestSubType": []
            },
``` 
 2. HMI and SDL are started
 3. Mobile app(REMOTE_CONTROL) is registered
 4. App is activated (HMI_FULL)

### Steps to reproduce:

1.  App sends a ButtonPress request with the following params: `{"moduleType":"RADIO","buttonName":"SOURCE","buttonPressMode":"LONG"} `

### Expected result:
Audio source switches in the background. No changes to app UI

### Actual result:

The HMI switches to new audio source and switches back to the app, resulting in a weird UI view
Source Switch

## Environment:
SDL: [release/8.2.0](https://github.com/smartdevicelink/sdl_core/tree/release/8.2.0)
HMI: release/5.8.0

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #692

This PR is **ready** for review.

### Testing Plan
Manual testing with RPC Builder

### Summary
Added a `transitionInBackground` method in AudioModel.js which handles changing the currentAudioModel and sending an OnInteriorVehicleData notification with the new source

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/model/media/AudioModel.js [hunk 1]
```diff
@@ -558,17 +594,52 @@ SDL.AudioModel = Em.Object.extend({
       }
     },
 
+    transitionInBackground(nextState){
```
Comment (jacobkeeler) [inline app/model/media/AudioModel.js:597]:
```suggestion
    changeAudioSource(nextState, isBackground) {
      if (!isBackground) {
        SDL.States.goToStates(nextState);
        return;
      }
```
Looks like we could move some of this logic into this function to make it more generic

File: app/model/media/AudioModel.js [hunk 2]
```diff
@@ -260,73 +260,109 @@ SDL.AudioModel = Em.Object.extend({
...
+          SDL.States.goToStates('media.player.radio');
+        } else {
+          this.transitionInBackground('media.player.radio')
+        }
       }
       SDL.RCModulesController.currentRadioModel.saveCurrentOptions();
-      SDL.RCModulesController.currentRadioModel.set('active', true);
+      if (!is_background) {
+        SDL.RCModulesController.currentRadioModel.set('active', true);
+     }
```
Comment (jacobkeeler) [inline app/model/media/AudioModel.js:311]:
```suggestion
      }
```

File: app/model/media/AudioModel.js [hunk 3]
```diff
@@ -260,73 +260,109 @@ SDL.AudioModel = Em.Object.extend({
...
-        SDL.States.goToStates('media.player.cd');
+        if (!is_background) {
+          SDL.States.goToStates('media.player.cd');
+        } else {
+          this.transitionInBackground('media.player.cd')
+        }
       }
+     if (!is_background) {
       this.onPlayerEnter(SDL.RCModulesController.currentAudioModel.cdModel, 'cd');
+     }
```
Comment (jacobkeeler) [inline app/model/media/AudioModel.js:274]:
```suggestion
      if (!is_background) {
        this.onPlayerEnter(SDL.RCModulesController.currentAudioModel.cdModel, 'cd');
      }
```

File: app/model/media/AudioModel.js [hunk 4]
```diff
@@ -260,73 +260,109 @@ SDL.AudioModel = Em.Object.extend({
     /**
      * Turn on CD
      */
-    turnOnCD: function () {
+    turnOnCD: function (event=null, is_background=false) {
```
Comment (jacobkeeler) [inline app/model/media/AudioModel.js:263]:
```suggestion
    turnOnCD: function (is_background=false) {
```
Doesn't look like this `event` parameter is used?

File: app/model/media/AudioModel.js [hunk 5]
```diff
@@ -558,17 +594,52 @@ SDL.AudioModel = Em.Object.extend({
...
     },
 
+    transitionInBackground(nextState){
+      SDL.RCModulesController.currentAudioModel.set('activeState', nextState);
+      if (FFW.RC.isSetVdInProgress) {
+        return;
+      }
+      let currentAudioModel = null;
+      switch (nextState) {
+        case 'media.player.radio': {
```
Comment (jacobkeeler) [inline app/model/media/AudioModel.js:604]: Might want to pass the audio model in? I dunno, this does seem a bit clunky. Not a huge deal I suppose though

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: app/model/media/AudioModel.js (hunk 5 above)
Comment (jacobkeeler) [reply app/model/media/AudioModel.js:604]: That or maybe getting the audio model can be a separate function?

File: app/model/media/AudioModel.js (hunk 4 above)
Comment (ShobhitAd) [reply app/model/media/AudioModel.js:263]: Not when the source is switched through an RPC request but when the "Go To CD" button is pressed (https://github.com/smartdevicelink/sdl_hmi/blob/master/app/view/infoView.js#L175) a DOM/Ember event is passed through to turnOnCD. This would overwrite the is_background with an object rather than a bool
Screenshot from 2022-09-21 11-13-44

**Review by jacobkeeler — APPROVED** [review]
