### PR TITLE
Fix sending of redundant notifications on app activation

### LINKED ISSUE #455: HMI sends OnUpdateFile and OnUpdateSubMenu notifications on Activate App
**Bug Report**
HMI sends OnUpdateFile and OnUpdateSubMenu notification on Activate App to SDL

**Precondition:**
1. SDL and HMI are started
2. Mobile device connected
3. Mobile app is registered and activated
4. SubMenu item is added with an image that does exist on file system
AddSubMenu( "menuIcon":\{ "value":"missing_file.png", "imageType" = "DYNAMIC"}, "menuName":"Submenu Name 1", "menuID":1 }
5. App is deactivated
On HMI -> Options -> Exit "USER_EXIT"
App hmiLevel is "NONE"
or (On HMI -> press button "Home" )
App hmiLevel is "LIMITED"

**Reproduction Steps:**
1) Activate App
HMI→SDL: SDL.ActivateApp("appID":ID)

**Observed Behavior:**
HMI sends OnUpdateSubMenu and OnUpdateFile notifications
HMI→SDL: UI.OnUpdateFile":{"appID":ID,"fileName":"File_reference_name/missing_file.png"}}
HMI→SDL: UI.OnUpdateSubMenu ({"appID":ID,"menuID":1,"updateSubCells":true}}
SDL→APP: OnUpdateSubMenu ({"menuID":1,"updateSubCells":true}}
SDL→APP: OnUpdateFile":{"fileName":"missing_file.png"}}

**Expected Behavior:**
HMI does not send OnUpdateSubMenu and OnUpdateFile notifications

**OS & Version Information**
HMI: https://github.com/LuxoftSDL/sdl_hmi/tree/develop(f712d4e)
SDL: https://github.com/LuxoftSDL/sdl_core/tree/develop(a36ea82)

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #455 

This PR is **not ready** for review.

### Testing Plan
Covered by manual checklist

### Summary
Looks like HMI sends redundant `OnUpdateFile` and `onUpdateSubMenu` notifications when application was deactivated and activated again. After clarifications, looks like it makes more sense to send such notifications just once for each submenu and for each image which was not loaded properly. Also, updated logic of sending `OnUpdateSubMenu` items to make a partial update only for visible part of menu.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by Ypostolov — APPROVED** [review]

**Comment by ShobhitAd** [comment]
@AKalinich-Luxoft please resolve merge conflicts on PR

**Comment by AKalinich-Luxoft** [comment]
> @AKalinich-Luxoft please resolve merge conflicts on PR

@ShobhitAd conflicts have been resolved in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/d5a51121b7d696a31cb9d93af99310b383af132d

File: app/controller/sdl/Abstract/Controller.js [hunk 1]
```diff
@@ -1758,6 +1758,53 @@ SDL.SDLController = Em.Object.extend(
...
+    /**
+     * @function onUpdateFile
+     * @param {String} fileName
+     * @description Checks whether provided file was requested from SDL or not
+     * and sends notification if file was not requested yet
+     */
+    onUpdateFile: function(fileName) {
+      if(SDL.SDLController.model && SDL.SDLController.model.appID) {
+        let model = SDL.SDLController.model;
+        if (model.cachedIconFileNamesList.indexOf(fileName) < 0) {
```
Comment (ShobhitAd) [inline app/controller/sdl/Abstract/Controller.js:1770]:
```suggestion
        if (!model.cachedIconFileNamesList.includes(fileName)) {
```
might be clearer since we only want to check if that fileName exists in the list

File: app/controller/sdl/Abstract/Controller.js [hunk 2]
```diff
@@ -1758,6 +1758,53 @@ SDL.SDLController = Em.Object.extend(
...
+    /**
+     * @function onUpdateSubMenu
+     * @param {Integer} menuID
+     * @description Checks whether provided menuID update was requested from SDL
+     * or not and sends notification if submenu was not updated yet
+     */
+    onUpdateSubMenu: function(menuID) {
+      if(SDL.SDLController.model && SDL.SDLController.model.appID) {
+        let model = SDL.SDLController.model;
+        if (model.cachedSubmenuIdsList.indexOf(menuID) < 0) {
```
Comment (ShobhitAd) [inline app/controller/sdl/Abstract/Controller.js:1786]:
```suggestion
        if (!model.cachedSubmenuIdsList.includes(menuID)) {
```

**Review by ShobhitAd — CHANGES_REQUESTED** [review]
Similar to how a `menuId` is removed from the `cachedSubMenuIdsList` when a `DeleteSubMenu` is received, shouldn't filenames be removed from `cachedIconFileNamesList` when an `onFileRemoved` is received?

**Comment by AKalinich-Luxoft** [comment]
> Similar to how a `menuId` is removed from the `cachedSubMenuIdsList` when a `DeleteSubMenu` is received, shouldn't filenames be removed from `cachedIconFileNamesList` when an `onFileRemoved` is received?

@ShobhitAd agree, makes sense. Added in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

File: app/controller/sdl/Abstract/Controller.js (hunk 1 above)
Comment (AKalinich-Luxoft) [reply app/controller/sdl/Abstract/Controller.js]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

File: app/controller/sdl/Abstract/Controller.js (hunk 2 above)
Comment (AKalinich-Luxoft) [reply app/controller/sdl/Abstract/Controller.js]: @ShobhitAd fixed in https://github.com/smartdevicelink/sdl_hmi/pull/460/commits/fc0ec0196e42cd5a8b20429f28b7b030fdb7c894

**Review by ShobhitAd — APPROVED** [review]
