### PR TITLE
Fix/Add Missing WEB_VIEW display capabilities

### LINKED ISSUE #686: Missing WEB_VIEW Display Capabilities
Currently, the `textFields` and `imageFields` params are missing from the display capabilites for WEB_VIEW. The following capabilities should be added for WEB_VIEW in `display_capabilities.js`

```json
"WEB_VIEW": {
        "displayCapabilities": {
            ...
            "textFields": [
                {
                    "name": "templateTitle",
                    "characterSet": "UTF_8",
                    "width": 100,
                    "rows": 1
                },
                {
                    "name": "alertText1",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "alertText2",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "alertText3",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "scrollableMessageBody",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "initialInteractionText",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "audioPassThruDisplayText1",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "audioPassThruDisplayText2",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "sliderHeader",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                },
                {
                    "name": "sliderFooter",
                    "characterSet": "UTF_8",
                    "width": 500,
                    "rows": 1
                }
            ],
            "imageFields": [
                {
                    "name": "alertIcon",
                    "imageTypeSupported": [
                        "GRAPHIC_BMP",
                        "GRAPHIC_JPEG",
                        "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                        "resolutionWidth": 105,
                        "resolutionHeight": 65
                    }
                },
                {
                    "name": "choiceImage",
                    "imageTypeSupported": [
                        "GRAPHIC_BMP",
                        "GRAPHIC_JPEG",
                        "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                        "resolutionWidth": 64,
                        "resolutionHeight": 64
                    }
                },
                {
                    "name": "choiceSecondaryImage",
                    "imageTypeSupported": [
                        "GRAPHIC_BMP",
                        "GRAPHIC_JPEG",
                        "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                        "resolutionWidth": 64,
                        "resolutionHeight": 64
                    }
                },
                {
                    "name": "cmdIcon",
                    "imageTypeSupported": [
                        "GRAPHIC_BMP",
                        "GRAPHIC_JPEG",
                        "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                        "resolutionWidth": 64,
                        "resolutionHeight": 64
                    }
                },
                {
                    "name": "subMenuIcon",
                    "imageTypeSupported": [
                      "GRAPHIC_BMP",
                      "GRAPHIC_JPEG",
                      "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                      "resolutionWidth": 64,
                      "resolutionHeight": 64
                    }
                },
                {
                    "name": "menuCommandSecondaryImage",
                    "imageTypeSupported": [
                      "GRAPHIC_BMP",
                      "GRAPHIC_JPEG",
                      "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                      "resolutionWidth": 105,
                      "resolutionHeight": 65
                    }
                  },
                  {
                    "name": "menuSubMenuSecondaryImage",
                    "imageTypeSupported": [
                      "GRAPHIC_BMP",
                      "GRAPHIC_JPEG",
                      "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                      "resolutionWidth": 105,
                      "resolutionHeight": 65
                    }
                  },
                  {
                    "name": "subtleAlertIcon",
                    "imageTypeSupported": [
                      "GRAPHIC_BMP",
                      "GRAPHIC_JPEG",
                      "GRAPHIC_PNG"
                    ],
                    "imageResolution": {
                      "resolutionWidth": 105,
                      "resolutionHeight": 65
                    }
                  }
            ],
            ...
        }
    }
```

### PR DESCRIPTION
**Pull request by ShobhitAd**
Fixes #686

This PR is **ready** for review.

### Testing Plan
1. Start policy server
2. Add the following entry in sdl_preloaded_pt.json

```json
            "45b2c12c-a289-4c08-b4e4-bee768bf0cf9": {
                "AppHMIType": [ "WEB_VIEW" ],
                "keep_context": false,
                "steal_focus": false,
                "priority": "NONE",
                "default_hmi": "NONE",
                "groups": ["Base-4", "WidgetSupport"],
                "hybrid_app_preference": "CLOUD",
                "enabled": false,
                "transport_type ": "WS"
            },
```

3. Change the `appStoreUrl` in Flags.js to `http://localhost:3000/api/v1/applications/store`
4. Start core and HMI
5. In the HMI, enable the "Hello Webengine3" app in the app store and activate the app
6. In the WEB_VIEW change the display layout to NON-MEDIA
7. Click on Options -> Return to WEB_VIEW

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by crokita — APPROVED** [review]

File: capabilities/display_capabilities.js [hunk 1]
```diff
@@ -1130,6 +1130,166 @@ SDL.templateCapabilities = {
...
+                    "imageTypeSupported": [
+                      "GRAPHIC_BMP",
+                      "GRAPHIC_JPEG",
+                      "GRAPHIC_PNG"
+                    ],
+                    "imageResolution": {
+                      "resolutionWidth": 105,
+                      "resolutionHeight": 65
+                    }
+                  }
```
Comment (jacobkeeler) [inline capabilities/display_capabilities.js:1291]: Missing `menuIcon`,  `vrHelpItem`, `turnIcon`, `showConstantTBTIcon`, and `showConstantTBTNextTurnIcon`

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: capabilities/display_capabilities.js [hunk 2]
```diff
@@ -1130,6 +1130,166 @@ SDL.templateCapabilities = {
...
+                    "characterSet": "UTF_8",
+                    "width": 500,
+                    "rows": 1
+                },
+                {
+                    "name": "sliderFooter",
+                    "characterSet": "UTF_8",
+                    "width": 500,
+                    "rows": 1
+                }
```
[the remark this answers is not in the document]
Comment (ShobhitAd) [reply capabilities/display_capabilities.js:1193]: Ah I was trying to match the WEB_VIEW capabilities with those in the generic hmi but I guess it makes sense that the navigation related textfields are not added in the generic hmi. 

That said, `menuName` and `secondaryText` should also probably be added in the generic hmi WEB_VIEW capabilities

File: capabilities/display_capabilities.js (hunk 1 above)
Comment (ShobhitAd) [reply capabilities/display_capabilities.js:1291]: I think the [webengine projection proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0273-webengine-projection-mode.md#1-template-web_view) mentions that `menuIcon` should not be a part of the WEB_VIEW capabilities

> 4. The WEB_VIEW template must not declare support in its WindowCapabilities for any `softButtonCapabilities`, the TextFields with name: `mainField1-4`, `mediaClock`, `mediaTrack`, nor the ImageFields with name: `softButtonImage`, `menuIcon`, `graphic`, or `secondaryGraphic`.

But I can add in the other capabilities you mentioned

Comment (ShobhitAd) [reply capabilities/display_capabilities.js]: Added in https://github.com/smartdevicelink/sdl_hmi/pull/688/commits/782bc5ca4258a040f0025ee9656795e8ff4872f1

File: capabilities/display_capabilities.js [hunk 3]
```diff
@@ -1130,6 +1130,166 @@ SDL.templateCapabilities = {
...
+                    "characterSet": "UTF_8",
+                    "width": 500,
+                    "rows": 1
+                },
+                {
+                    "name": "alertText3",
+                    "characterSet": "UTF_8",
+                    "width": 500,
+                    "rows": 1
+                },
```
[the remark this answers is not in the document]
Comment (ShobhitAd) [reply capabilities/display_capabilities.js:1211]: Added in https://github.com/smartdevicelink/sdl_hmi/pull/688/commits/d12e03a814b11eaef5287c0afe83868d704335ec

File: capabilities/display_capabilities.js (hunk 1 above)
Comment (jacobkeeler) [reply capabilities/display_capabilities.js]: Ah, based on this proposal, it looks like the web view is supposed to display the menu button itself, so in that case we should probably also remove `menuTitle`

**Review by jacobkeeler — APPROVED** [review]

**Comment by jacobkeeler** [comment]
Approving, though I will note two unrelated issues I found during testing
1. It seems `ONSCREEN_PRESETS` is missing from the template list of several of the templates.
2. Using the flow you gave in the PR description, I get an error. If you try to switch to `NON-MEDIA` from `WEB_VIEW` and back, it seems several things go wrong with the HMI state at the moment.

**Review by crokita — APPROVED** [review]
