### PR TITLE
Fix UNSUPPORTED_RESOURCE result code for images

### LINKED ISSUE #443: HMI aborts AlertManeuver, PerformInteraction requests with STATIC images
**Precondition:**
1. SDL and HMI are started
2. Mobile app is registered and activated
3. CreateInteractionChoiceSet is added with STATIC image as precondition for PerformInteraction

**Reproduction Steps:**
1. Request AlertManeuver/PerformInteraction RPC with `STATIC` image

**Expected behavior:**
1. HMI processes the request but no not show the icon
2. HMI responds with `UNSUPPORTED_RESOURCE` resultCode + the message of the kind `Image of '%' type is not supported on HMI. Request was not displayed`
3. SDL responds with `UNSUPPORTED_RESOURCE` resultCode and success=true to mobile app (also with choiceId in case of PerformInteraction request)

**Observed behavior:**
1. HMI does not process the request
2. HMI responds with `WARNINGS` resultCode to AlertManeuver and `UNSUPPORTED_RESOURCE` resultCode to PerformInteraction  + the message of the kind `Image of '%' type is not supported on HMI. Request was not processed`
image

**OS & Version Information**
OS: Ubuntu 18.04
SDL: release/7.0.0 54246454
HMI: develop 931877c

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #443 and #442 and #445 

This PR is **ready** for review.

### Testing Plan
Covered by manual tests

### Summary
Make HMI to respond with the proper result code in case when STATIC image is received. Also removed redundant and commented code to make things cleaner.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by Ypostolov — APPROVED** [review]

**Comment by theresalech** [comment]
@AKalinich-Luxoft, given the size of these changes and time constraints (Steering Committee is currently reviewing Core 7.0 Release Candidate for approval, and release of both Core 7.0 and SDL HMI 5.4 are planned for tomorrow, 11/5), we will plan to review this PR for the following SDL HMI release.

**Review by jacobkeeler — CHANGES_REQUESTED** [review]

File: ffw/TTSRPC.js [hunk 1]
```diff
@@ -145,28 +145,6 @@ FFW.TTS = FFW.RPCObserver.create(
...
-                this.errorResponsePull[request.id].code, request.id,
-                request.method,
-                'Unsupported ' + this.errorResponsePull[request.id].type +
-                ' type. Request was not processed.'
-              );
-              this.errorResponsePull[request.id] = null;
-              //
-              return;
-            }
-          }
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply ffw/TTSRPC.js:169]: @jacobkeeler nice catch. Fixed in https://github.com/smartdevicelink/sdl_hmi/pull/450/commits/3fef8dc711af9ecbe8c9f0c1f4cedae8b5158d99

File: app/model/sdl/Abstract/Model.js [hunk 2]
```diff
@@ -1041,7 +1041,7 @@ SDL.SDLModel = Em.Object.extend({
         for(var i = 0; i < SDL.SDLModel.imageCheckList[requestID].length; i++) {
           var formattedImgPath = this.src.substring(this.src.indexOf('://') + '://'.length);
           var path = SDL.SDLModel.imageCheckList[requestID][i].path;
-          if(path === formattedImgPath) {
+          if (formattedImgPath.endsWith(path)) {
```
[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply app/model/sdl/Abstract/Model.js]: @jacobkeeler I remember there was an issue when `this.src` returns me just `icon.png` without an absolute path so validation was never finished, however I am not able to reproduce this now. I reverted that change in https://github.com/smartdevicelink/sdl_hmi/pull/450/commits/3fef8dc711af9ecbe8c9f0c1f4cedae8b5158d99

[the remark this answers is not in the document]
Comment (AKalinich-Luxoft) [reply app/model/sdl/Abstract/Model.js]: @jacobkeeler seems like I found what was the issue. It is happening when some RPC passes image with relative path to validation. For example, `Alert` uses image `images/sdl/Warning.png` however this is a relative path so in case if this will be validated, `formattedImgPath` will never be equal to `path` here and element with required index will never be found and set. As a result, image validation result will never be received back by RPC regardless of another images types and extensions.
I simplified that function and just set index as a property of `this` and use it to set the element by that index in the array so this `for` loop is not required anymore. I pushed that commit into #462  - https://github.com/smartdevicelink/sdl_hmi/pull/462/commits/62be9bc1f3ccad2b5a6e1911fca1fae47df71a87 because it can't be verified without these changes.
Actually, these two pull requests have a lot of intersections and I can propose to merge one PR into another and review them together. Otherwise, we can review and merged them separately, but some conflicts should be resolved then.
Please let me know what do you think about that?

[the remark this answers is not in the document]
Comment (jacobkeeler) [reply app/model/sdl/Abstract/Model.js]: Eh, considering that my review of this PR is almost done as-is, and we would need to fix merge conflicts in any case, I say that we can just go forward with reviewing them separately

File: ffw/UIRPC.js [hunk 3]
```diff
@@ -2007,67 +1927,33 @@ FFW.UI = FFW.RPCObserver.create(
...
-        }
-        if (manualTextEntry != null) {
-          JSONMessage.result.manualTextEntry = manualTextEntry;
-        }
+        this.sendUIResult(
+          resultCode,
+          requestID,
+          'UI.PerformInteraction',
+          info,
+          params
```
Comment (jacobkeeler) [inline ffw/UIRPC.js:1947]: As a note, if a PerformInteraction request is sent with MANUAL_ONLY, Core will mark the response as `success: false` if an UNSUPPORTED_RESOURCE code is sent.

Comment (jacobkeeler) [reply ffw/UIRPC.js:1947]: Seems this is the case with `Alert` as well.

Comment (jacobkeeler) [reply ffw/UIRPC.js:1947]: @AKalinich-Luxoft Perhaps we should keep it so these cases return `WARNINGS` for now? That or we could submit a fix for this issue alongside this PR. Let me know your thoughts on the matter

Comment (AKalinich-Luxoft) [reply ffw/UIRPC.js:1947]: @jacobkeeler so the fix was to return UNSUPPORTED_RESOURCE instead of WARNINGS in these cases.
Regarding `success:false` - do you mean wrong SDL behavior in that case? If so, I agree that new SDL issue should be created and we can work on fix for that further

Comment (AKalinich-Luxoft) [reply ffw/UIRPC.js:1947]: @jacobkeeler I also see the issues like https://github.com/smartdevicelink/sdl_core/issues/1596 which looks like describe the same case

Comment (jacobkeeler) [reply ffw/UIRPC.js:1947]: hmm, don't know exactly what happened with that issue, the one difference in the description is that it specifies is that `UNSUPPORTED_RESOURCE` is sent for `VR.PerformInteraction` instead of `UI.PerformInteraction`. At the moment, it looks like the SDL HMI will send `WARNINGS` for `VR.PerformInteraction` if unsupported phonemes are used, so it's possible that I attempted that and misinterpreted the results. Seems that the issue is still present though, so I will reopen the issue.

Comment (jacobkeeler) [reply ffw/UIRPC.js:1947]: Alright, I think I can approve this PR for now and I'll submit a fix for https://github.com/smartdevicelink/sdl_core/issues/1596 to go along with this

**Review by jacobkeeler — APPROVED** [review]
