### PR TITLE
Fix/Get Display Capabilities based on template

### LINKED ISSUE #586: HMI does not update capabilities based on template
When switching templates while an app is subscribed to `DISPLAYS` system capabilities, the HMI should send an `OnSystemCapabilityUpdated` message with the new template's capabilities, but instead it sends a static set of capabilities from `Abstract/data.js` (which also currently have incorrect `buttonCapabilities`, since they include RC buttons).

Reproduction Steps:

1. App is registered with `MEDIA` and `NAVIGATION` app HMI types
2. App sends `GetSystemCapability(DISPLAYS)` with `subscribe=true`
3. App sends `Show` request with `templateConfiguration`, `templateName="NON-MEDIA"`

Expected behavior:

App receives `SUCCESS` response to `Show` request
App receives `OnSystemCapabilityUpdated(DISPLAYS)` with the display capabilities for the `NON-MEDIA` template

Actual behavior:

App receives `SUCCESS` response to `Show` request
App receives `OnSystemCapabilityUpdated(DISPLAYS)` with a set of display capabilities which does not correspond to any template.

### PR DESCRIPTION
**Pull request by ShobhitAd**
Implements/Fixes #586 

This PR is **ready** for review.

### Testing Plan
- Test changing the template for `Show` and `SetDisplayLayout` and observe the `OnSystemCapabilityUpdated(DISPLAYS)` notification.
- Test adding a widget using `CreateWindow` and observe the `OnSystemCapabilityUpdated(DISPLAYS)` notification.

### Summary
- Added method `getDisplayCapabilities` in Controller.js
- Replaced usages of `getDefaultCapabilities` with `getDisplayCapabilities` in UIRPCs.js

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/controller/sdl/Abstract/Controller.js [hunk 1]
```diff
@@ -1639,6 +1639,36 @@ SDL.SDLController = Em.Object.extend(
...
+
+      // MAIN window
+      let displayCapabilities = [SDL.templateCapabilities[appModel.templateConfiguration.template].displayCapabilities];
+      displayCapabilities[0].windowTypeSupported = windowTypeSupportedMain;
+
+      // WIDGET windows
+      appModel.getWidgetModels().forEach(element => {
+        let capability = SDL.templateCapabilities[element.content.templateConfiguration.template].displayCapabilities;
+        capability.windowTypeSupported = windowTypeSupportedWidget;
+        displayCapabilities.concat(capability)
```
[the remark this answers is not in the document]
Comment (ShobhitAd) [reply app/controller/sdl/Abstract/Controller.js]: Based on https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml#L3815, it looks like the `OnSystemCapabilityUpdated` notification should only contain capabilities for the updated window. Added the changes in https://github.com/smartdevicelink/sdl_hmi/pull/590/commits/ce1db5c94e3df69fab479359422047ca2097cdae

So when you send a `CreateWindow` request the returned OSCU notification should only contain the capabilities for the widget(should include the correct `windowID`) but to get the capabilities for all windows you'll have to send `GetSystemCapability(DISPLAYS)` request

File: app/controller/sdl/Abstract/Controller.js [hunk 2]
```diff
@@ -1643,28 +1643,37 @@ SDL.SDLController = Em.Object.extend(
...
      */
-    getDisplayCapabilities: function(appID){
-      let appModel = SDL.SDLController.getApplicationModel(appID);
-      const windowTypeSupportedMain = SDL.SDLModelData.defaultWindowCapability["MAIN"].systemCapability.displayCapabilities[0].windowTypeSupported;
-      const windowTypeSupportedWidget = SDL.SDLModelData.defaultWindowCapability["WIDGET"].systemCapability.displayCapabilities[0].windowTypeSupported;
-
-      // MAIN window
-      let displayCapabilities = [SDL.templateCapabilities[appModel.templateConfiguration.template].displayCapabilities];
-      displayCapabilities[0].windowTypeSupported = windowTypeSupportedMain;
+    getDisplayCapabilities: function(appID, windowID){
```
Comment (iCollin) [inline app/controller/sdl/Abstract/Controller.js:1649]: Now that this method just returns one displayCapability, I think naming it `getDisplayCapability` might be more appropriate.

**Review by iCollin — APPROVED** [review]

File: app/controller/sdl/Abstract/Controller.js (hunk 2 above)
Comment (ShobhitAd) [reply app/controller/sdl/Abstract/Controller.js]: Agreed. Changed in https://github.com/smartdevicelink/sdl_hmi/pull/590/commits/ba1b34795f09069d04291c3f51ee0ec8e722df27
