### PR TITLE
send choice_id when an interaction succeeds

### LINKED ISSUE #222: A `PerformInteraction` response does not return a `choiceID` if the choice set was created with a static icon
### Bug Report
A `PerformInteraction` response does not return a `choiceID` if the choice set was created with a static icon.

##### Reproduction Steps
1. Send a `CreateInteractionChoiceSet` with a single choice. The choice should have an `image` with an `imageType` of `STATIC`. A `CreateInteractionChoiceSet` will be returned with a `resultCode` of `SUCCESS`.
    ```
    Send RPC CreateInteractionChoiceSet (request), id: 4
    {
    choiceSet =     (
        "{\n    choiceID = 1;\n    image = \"{\\n    imageType = STATIC;\\n    isTemplate = 1;\\n        value = 0x7D;\\n}\";\n    menuName = one;\n    vrCommands =     (\n        one\n    );\n}"
    );
    interactionChoiceSetID = 1;
    }
    ```

2. Send a `PerformInteraction` request with the choice from step 1. The `interactionMode` should be `MANUAL_ONLY`.
    ```
    Send RPC PerformInteraction (request), id: 11
    {
    initialText = "Testing Manual";
    interactionChoiceSetIDList =     (
        1
    );
    interactionLayout = "LIST_ONLY";
    interactionMode = "MANUAL_ONLY";
    timeout = 10000;
    }
    ```

3. When the choice set appears on the HMI, select the only item in list (i.e. the cell with menu name "one" from step 1)

##### Expected Behavior
The `PerformInteraction` response returns the `choiceID` of the selected choice. 

##### Observed Behavior
The `PerformInteraction` response returns a `success` of `1` and a `resultCode` of `UNSUPPORTED_RESOURCE`. No `choiceID` is returned.
```
Message received: PerformInteraction (response), id: 11
{
    info = "Unsupported STATIC type. Available data in request was processed.";
    resultCode = "UNSUPPORTED_RESOURCE";
    success = 1;
}
```

##### OS & Version Information
* SDL HMI Version: 5.1.0 (develop branch)
* SDL Core Version: 5.1.3 (develop branch)
* Testing Against: The SDL iOS Swift example app.

##### Test Case, Sample Code, and / or Example App
https://github.com/smartdevicelink/sdl_ios/tree/master/Example%20Apps/Example%20Swift

### PR DESCRIPTION
**Pull request by iCollin**
the unsupported resource code from having an unsupported image type was preventing useful information from reaching mobile, when an interaction succeeds, we should send the command ID and proceed with WARNINGS and an info string

Implements/Fixes #222 

This PR is **ready** for review.

### Testing Plan
manually

### Summary
When an interaction succeeds, but also has an error associated with an unsupported imageType or SpeechCapabilities type, send a success response with code WARNINGS and a helpful info string.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by NicoleYarroch** [comment]
The fix now returns a `choiceID` but I am not getting the `info` field that should explain why the `resultCode` is `WARNINGS`.

File: ffw/UIRPC.js [hunk 1]
```diff
@@ -1233,26 +1233,26 @@ FFW.UI = FFW.RPCObserver.create(
...
-            'code': this.errorResponsePull[requestID].code,
-            'message': 'Unsupported ' + this.errorResponsePull[requestID].type +
-            ' type. Available data in request was processed.',
-            'data': {
-              'method': 'UI.PerformInteraction'
-            }
+          'result': {
+            'code': SDL.SDLModel.data.resultCode.WARNINGS,
+            'method': 'UI.PerformInteraction',
+            'message': 'Unsupported ' + this.errorResponsePull[requestID].type
```
Comment (jacobkeeler) [inline ffw/UIRPC.js]: This reason this message is not being received might be because you changed the structure to the normal response format. The `message` field is only defined in the error format, so that should be used in this case.

Comment (iCollin) [inline ffw/UIRPC.js]:
```suggestion
            'info': 'Unsupported ' + this.errorResponsePull[requestID].type 
```
@jacobkeeler You're correct, message should be info in the case of a successful response.

Comment (iCollin) [reply ffw/UIRPC.js]: `message` changed to `info` in https://github.com/smartdevicelink/sdl_hmi/pull/223/commits/120e9f01b2d719d4b7759839561cca81f74da647

Comment (jacobkeeler) [reply ffw/UIRPC.js]: Still not receiving `info` on the mobile end, I'm pretty sure you need to convert this to the error format to send a message.

**Comment by NicoleYarroch** [comment]
I tested with the develop branch of sdl_core and it is working as expected. I am now getting the `choiceID` and `info`.
