### PR TITLE
Fix/fix get ivd response for climate

### LINKED ISSUE #305: HMI provides all CLIMATE data in case climateEnable=false
### Bug Report
HMI provides all `CLIMATE` data in case `climateEnable=false`

##### Reproduction Steps
1. Start SDL and HMI
2. `REMOTE_CONTROL` app is registered
3. Go to tab `Climate` and press `Climate OFF` button for a turning off 
4. Mobile app requests `GetInteriorData(subscription=false)`

##### Expected Behavior
HMI responds with only climateEnable=false parameter:

> HMI -> SDL : {"jsonrpc":"2.0","id":332,"result":{"code":0,"method":"RC.GetInteriorVehicleData","moduleData":{"moduleType":"CLIMATE","moduleId":"d38e4a05-b17c-28e3-9d38-e4a05b17c28e","climateControlData":{"climateEnable":false}}}}

##### Observed Behavior
HMI sends all `CLIMATE` data: 

> HMI -> SDL : {"jsonrpc":"2.0","id":332,"result":{"code":0,"method":"RC.GetInteriorVehicleData","moduleData":{"moduleType":"CLIMATE","moduleId":"d38e4a05-b17c-28e3-9d38-e4a05b17c28e","climateControlData":{"fanSpeed":0,"currentTemperature":{"unit":"CELSIUS","value":20},"desiredTemperature":{"unit":"CELSIUS","value":25},"acEnable":true,"circulateAirEnable":true,"autoModeEnable":true,"defrostZone":"FRONT","dualModeEnable":true,"acMaxEnable":true,"ventilationMode":"UPPER","heatedWindshieldEnable":false,"heatedRearWindowEnable":false,"heatedSteeringWheelEnable":false,"heatedMirrorsEnable":false,"climateEnable":false}}}}

##### OS & Version Information
* sdl_hmi branch: [develop](https://github.com/smartdevicelink/sdl_hmi/tree/develop)
* commit: e8baa2d8f3f4b43d261323e0dd2c30843509e925
* sdl_core branch: https://github.com/smartdevicelink/sdl_core/tree/6.1.0_RC

### PR DESCRIPTION
**Pull request by AKalinich-Luxoft**
Fixes #305 

This PR is **ready** for review.

### Testing Plan
Covered by manual testing

### Summary
Changelog:
- Removed unused code from climate controller
- Renamed climate control functions according to their exact logic
- Add disabled binding for temperature buttons
- Fixed logic for getting climate control data required by GetIVD request

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/model/ClimateControlModel.js [hunk 1]
```diff
@@ -203,12 +206,19 @@ SDL.ClimateControlModel = Em.Object.extend({
...
+  },
 
-    return result;
+  /**
+   * @description Gets climate data object with filtered properties
+   */
+  getClimateControlData: function() {
+    const climate_data = this.generateClimateControlData();
+    const filter_properties = this.getDataForSending();
+    return SDL.SDLController.filterObjectProperty(climate_data, filter_properties);
```
Comment (mkorniichuk) [inline app/model/ClimateControlModel.js:217]: @AKalinich-Luxoft As far as i understood, `getDataForSending` will also call `generateClimateControlData` and filter it. And `filterObjectProperty` will keep `filter_properties` from `climate_data`. Why don't just return `filter_properties`?

Comment (AKalinich-Luxoft) [reply app/model/ClimateControlModel.js:217]: @mkorniichuk its little bit tricky :)
`getDataForSending()` returns array of fields which are eligible for sending within current circumstances. That's why we need to do an extra step, generate data one more time and apply that array to generated data as we need to return an object in `getClimateControlData()`

**Review by iCollin — APPROVED** [review]
