### PR TITLE
Fix/double send of on language change and on systeminfo changed

### LINKED ISSUE #256: OnLanguageChange and OnSystemInfoChanged are sent twice
### Bug Report
OnLanguageChange and OnSystemInfoChanged are sent twice

##### Reproduction Steps
1. SDL and HMI are started
2. App is registered
3. Change language on HMI

##### Expected Behavior
HMI sends OnLanguageChange and OnSystemInfoChanged once to SDL

##### Observed Behavior
```
FFW.UI.OnLanguageChange
RPCClient.js:317 HMI -> SDL [15:17:6:13]: {"jsonrpc":"2.0","method":"UI.OnLanguageChange","params":{"language":"DE-DE"}}
BasicCommunicationRPC.js:1036 FFW.BasicCommunication.OnSystemInfoChanged
RPCClient.js:317 HMI -> SDL [15:17:6:17]: {"jsonrpc":"2.0","method":"BasicCommunication.OnSystemInfoChanged","params":{"language":"DE-DE"}}
UIRPC.js:1589 FFW.UI.OnLanguageChange
RPCClient.js:317 HMI -> SDL [15:17:6:20]: {"jsonrpc":"2.0","method":"UI.OnLanguageChange","params":{"language":"DE-DE"}}
BasicCommunicationRPC.js:1036 FFW.BasicCommunication.OnSystemInfoChanged
RPCClient.js:317 HMI -> SDL [15:17:6:22]: {"jsonrpc":"2.0","method":"BasicCommunication.OnSystemInfoChanged","params":{"language":"DE-DE"}}
RPCClient.js:137 SDL -> HMI [15:17:6:126]: {"id":262,"jsonrpc":"2.0","method":"BasicCommunication.UpdateAppList","params":{"applications":[]}}
```

##### OS & Version Information
* SDL: https://github.com/smartdevicelink/sdl_core/tree/release/6.0.0 (tag RC_2)
https://github.com/smartdevicelink/sdl_core/tree/develop
* HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop
(bd53f11339ee4d95a41caf5e5edf4ae0839d5957)
* SPT: https://rink.hockeyapp.net/apps/dbc7db5274027027262185753824e34d
Version 20191028-Nightly-Android (1034)

### PR DESCRIPTION
**Pull request by YarikMamykin**
Fixes #256 

This PR is **ready** for review.

### Testing Plan
Manual testing by steps described in #256 

### Summary
There is known bug in old version of Ember.js (specifically 1.0, which is currently used) - observers of _SelectView_ item are noticed twice per each event. That is why `OnLanguageChanged` and `OnSystemInfoChanged` notifications come twice.
Implemented simple mechanism of blocking second notifications sending.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/controller/sdl/Abstract/Controller.js [hunk 1]
```diff
@@ -875,21 +875,64 @@ SDL.SDLController = Em.Object.extend(
...
-        SDL.SDLModel.data.hmiUILanguage
-      );
+      FFW.BasicCommunication.OnSystemInfoChanged(SDL.SDLModel.data.hmiUILanguage);
     }.observes('SDL.SDLModel.data.hmiUILanguage'),
     /**
      * Method to set language for TTS and VR components with parameters sent
      * from SDLCore to UIRPC
      */
     onLanguageChangeTTSVR: function() {
+      if (!this.canNotifyOnLanguageChange("VR")) {
```
Comment (AKalinich-Luxoft) [inline app/controller/sdl/Abstract/Controller.js]: @YarikMamykin it can be done in a simpler way:
1. Remove `.observes` from function
2. Find the control bound to this value
3. If it is a `Em.Select` you can declare `change` function inside of it and just call `onLanguageChangeTTSVR` from that callback

Comment (YarikMamykin) [reply app/controller/sdl/Abstract/Controller.js]: @AKalinich-Luxoft , unfortunately it doesn't work. In such case selected value will be changed with latency. 
For example if you choose FR-CA language and current language is EN-US, then notification will send updated language value = **EN-US**! After that you can choose another language and only then FR-CA language will be displayed.

Comment (AKalinich-Luxoft) [reply app/controller/sdl/Abstract/Controller.js]: @YarikMamykin use `this.selection` in `change` and pass it as a parameter to `onLanguageChangeTTSVR` then

Comment (YarikMamykin) [reply app/controller/sdl/Abstract/Controller.js]: @AKalinich-Luxoft , yes, this idea works well! Thanks for the tip!
Take a look at https://github.com/smartdevicelink/sdl_hmi/pull/263/commits/51d301375d82343fc093be12889d4076040e68f7
