### PR TITLE
Fix closeButton formatting for AlertManeuver

### LINKED ISSUE #536: HMI AlertManeuver pop-up is shown in case Navi.AlertManeuver request contains only appID
**Description:**
HMI AlertManeuver pop-up is shown in case Navi.AlertManeuver request contains only appID

**Precondition:**
1. SDL and HMI are started
2.  Media mobile app is registered and activated

**Steps to reproduce:**
1. Mobile app requests AlertManeuver RPC without softButtons

**Expected result:**
HMI does not show AlertManeuver pop-up, shows only TTS.Speak related to AlertManeuver request

**Actual result:**
HMI shows the empty AlertManeuver pop-up

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

### PR DESCRIPTION
**Pull request by jacobkeeler**
Fixes #536 

This PR is **ready** for review.

### Testing Plan
Send AlertManeuver without softbuttons, popup should appear with a centered "Close" button

### Summary
Center close button when present in AlertManeuver popup

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/view/sdl/AlertManeuverPopUp.js [hunk 1]
```diff
@@ -152,7 +149,8 @@ SDL.AlertManeuverPopUp = Em.ContainerView.create(
      */
     addSoftButtons: function(params) {
       const softButtons = params.softButtons;
-      if (!softButtons) {
+      if (!softButtons || softButtons.length == 0) {
```
Comment (JackLivio) [inline app/view/sdl/AlertManeuverPopUp.js:152]: I think the close button needs to be added if there are softbuttons included?

Comment (jacobkeeler) [reply app/view/sdl/AlertManeuverPopUp.js:152]: I was following the existing behavior in this case, which was to only show the close button if app-defined buttons were not present. I think the current behavior at least matches the description in the API, though I do think it could be interpreted either way:
```
        <param name="softButtons" type="SoftButton" minsize="0" maxsize="3" array="true" mandatory="false">
            <description>If omitted on supported displays, only the system defined "Close" SoftButton shall be displayed.</description>
        </param>
```

**Review by JackLivio — APPROVED** [review]
