### PR TITLE
Check valid model object

### LINKED ISSUE #541: HMI Uncaught TypeError: Cannot read property 'get' of null
**Description:**
HMI Uncaught TypeError: Cannot read property 'get' of null

**Precondition:**
1. SDL and HMI are started
2. Mobile device connected
3. Mobile app is registered and activated
4. SubMenu item is added
AddSubMenu("menuID":1, "menuName":"Submenu Name 1")
5. Nested submenu item is added in the previous submenu
Send AddSubMenu(parentID=1, "menuID":2)
6.  "Submenu Name 2" button is displayed on HMI 
On HMI "Options" -> "Submenu Name 1"

**Steps to reproduce:**
1. On HMI -> press button "i" 

**Expected result:**
App is deactivated and there are no error messages in HMI console
HMI -> SDL: BasicCommunication.OnAppDeactivated:{"appID": ... }}

**Actual result:**
App is deactivated and logs the error
HMI -> SDL: BasicCommunication.OnAppDeactivated:{"appID": ... }}

optionsView.js:68 Uncaught TypeError: Cannot read property 'get' of null
    at d.onOptionsPageChanged [as pageChangeListener] (optionsView.js:68)
    at d.onCurrentPageChange (List.js:118)
    at d.afterRender (List.js:232)
    at d [as afterRender] (ember-1.0.pre.min.js:14)
    at d.renderToBuffer (ember-1.0.pre.min.js:16)
    at d.createElement (ember-1.0.pre.min.js:16)
    at d.insertElement (ember-1.0.pre.min.js:16)
    at d.invokeForState (ember-1.0.pre.min.js:16)
    at c (ember-1.0.pre.min.js:14)
    at j (ember-1.0.pre.min.js:14)

**Environment:**
SDL: https://github.com/smartdevicelink/sdl_core/tree/7.1.0-RC1
HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop (7fad546)
SPT: SPT: 20210305-Android (1076)

### PR DESCRIPTION
**Pull request by JackLivio**
Implements/Fixes #541 

This PR is **Ready** for review.

### Testing Plan
Navigate to a nested submenu, then click climate or settings button to navigate away from app.

### Summary
Adds null check to model object in case app has been deactivated.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: app/view/sdl/shared/optionsView.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ SDL.OptionsView = SDL.SDLAbstractView.create(
         SDL.OptionsView.commands.items.length);
 
       let items = SDL.OptionsView.commands.items;
-      let menu_nested_items = SDL.SDLController.model.get('commandsList');
+      let menu_nested_items = SDL.SDLController.model?.get('commandsList');
       for (let i = start_index; i < end_index; ++i) {
         const menuID = items[i].params.menuID;
         if (menuID && menuID >= 0 && menu_nested_items[menuID].length === 0) {
```
Comment (iCollin) [inline app/view/sdl/shared/optionsView.js:71]:
```suggestion
        if (menuID > 0 && menu_nested_items[menuID]?.length === 0) {
```

File: app/view/sdl/shared/optionsView.js [hunk 2]
```diff
@@ -65,7 +65,7 @@ SDL.OptionsView = SDL.SDLAbstractView.create(
         SDL.OptionsView.commands.items.length);
 
       let items = SDL.OptionsView.commands.items;
-      let menu_nested_items = SDL.SDLController.model.get('commandsList');
+      let menu_nested_items = SDL.SDLController.model?.get('commandsList');
```
Comment (iCollin) [inline app/view/sdl/shared/optionsView.js:68]:
```suggestion
      let menu_nested_items = SDL.SDLController.model?.get('commandsList') ?? {};
```

**Review by iCollin — COMMENTED** [review]
If `SDLController.model` is null, `menu_nested_items` will be null, and an error will be thrown when you try to access it later in the loop: `menu_nested_items[menuID].length`

There are many ways to solve this but I think these two suggestions below would make it so this function cannot throw on invalid model

**Review by iCollin — APPROVED** [review]
